table CandidatoRedSocial
	lineageTag: 9f1d1725-a6b9-49c4-a642-3101ef9bf8cd

	measure 'Total Seguidores TikTok' =
			
			SUM(CandidatoRedSocial[Seguidores])
		lineageTag: 1331eeee-dea8-4374-bcc4-4bd6ec4fbeee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IdCandidatoRed
		dataType: int64
		formatString: 0
		lineageTag: 152a5576-b367-425d-b48c-654e4c6ea2d8
		summarizeBy: none
		sourceColumn: IdCandidatoRed

		annotation SummarizationSetBy = User

	column IdCandidato
		dataType: int64
		formatString: 0
		lineageTag: ceb158ea-8272-4ee2-9e8d-70f8f9a0224e
		summarizeBy: none
		sourceColumn: IdCandidato

		annotation SummarizationSetBy = User

	column IdRedSocial
		dataType: int64
		formatString: 0
		lineageTag: fc0a8a44-9c97-4b08-a27d-7bf055db4e71
		summarizeBy: none
		sourceColumn: IdRedSocial

		annotation SummarizationSetBy = Automatic

	column Tiene
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 21e64bde-ecf2-4732-95ca-fb82a74f1c58
		summarizeBy: none
		sourceColumn: Tiene

		annotation SummarizationSetBy = Automatic

	column MotivoNoTiene
		dataType: string
		lineageTag: 98f9dd73-1302-4aca-af8b-3cc811c920d3
		summarizeBy: none
		sourceColumn: MotivoNoTiene

		annotation SummarizationSetBy = Automatic

	column Usuario
		dataType: string
		lineageTag: d6106be0-c18c-4322-a67c-524ddd67005d
		summarizeBy: none
		sourceColumn: Usuario

		annotation SummarizationSetBy = Automatic

	column CantidadVideos
		dataType: int64
		formatString: 0
		lineageTag: dff03277-193e-4d36-8bf4-b32783d99788
		summarizeBy: none
		sourceColumn: CantidadVideos

		annotation SummarizationSetBy = User

	column Seguidores
		dataType: double
		lineageTag: 632da5ce-3975-4167-acad-a2ed672f8fba
		summarizeBy: none
		sourceColumn: Seguidores

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Likes
		dataType: int64
		lineageTag: a3251317-48d1-4d69-b072-811eeecd0c12
		summarizeBy: none
		sourceColumn: Likes

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Videos
		dataType: int64
		formatString: 0
		lineageTag: 3c325439-5763-4978-b8aa-23df8a6625c6
		summarizeBy: sum
		sourceColumn: Videos

		annotation SummarizationSetBy = Automatic

	partition CandidatoRedSocial = m
		mode: import
		source =
				let
				    Origen = Sql.Database("sql-candidatos2026-dev-w3-z0lh9d.database.windows.net", "Elecciones2026DW"),
				    dbo_CandidatoRedSocial = Origen{[Schema="dbo",Item="CandidatoRedSocial"]}[Data]
				in
				    dbo_CandidatoRedSocial

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

