table RTC_DetalleContratosEstado
	lineageTag: c9e125dd-7766-496c-93b9-ddc7cc2530f1

	column Candidato
		dataType: string
		lineageTag: 823a4dba-1329-4d6d-816c-48409b2dd2c9
		summarizeBy: none
		sourceColumn: Candidato

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: f7a588ce-8ab8-45ed-8a34-bdea61e7c851
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		lineageTag: 80750669-71f6-4671-af48-aff6402d14f2
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column Detalle
		dataType: string
		lineageTag: e459d0ce-f0ac-489a-a7e8-f2f00cdacf6e
		summarizeBy: none
		sourceColumn: Detalle

		annotation SummarizationSetBy = Automatic

	column Electo
		dataType: string
		lineageTag: 538bbdb5-72f0-4463-93aa-de8de2fde39e
		summarizeBy: none
		sourceColumn: Electo

		annotation SummarizationSetBy = Automatic

	column Fuente
		dataType: string
		lineageTag: e0f4a182-d25d-4c91-b675-97356d3041ed
		summarizeBy: none
		sourceColumn: Fuente

		annotation SummarizationSetBy = Automatic

	partition RTC_DetalleContratosEstado = m
		mode: import
		source =
				let
				  Origen = Csv.Document(File.Contents("C:\Users\DIEGO\Downloads\PROYECTO_SI885_2026-II-U2_DASHBOARDELECTORAL-main\data\RTC_ComparativaDetalle.csv"), [Delimiter = ",", Columns = 6, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(Origen, {{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}}, "es"),
				  #"Encabezados promovidos" = Table.PromoteHeaders(#"Tipo de columna cambiado", [PromoteAllScalars=true]),
				  #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Candidato", type text}, {"Categoria", type text}, {"Item", type text}, {"Detalle", type text}, {"Electo", type text}, {"Fuente", type text}}),
				  #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado", each [Categoria] = "Contratos con el Estado")
				in
				  #"Filas filtradas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

